name: Welcome and Auto-Comment on Issue

on:
  issues:
    types: [opened]

jobs:
  on-issue-open:
    runs-on: ubuntu-latest
    permissions:
      issues: write

    steps:
      - name: Welcome first-time issue contributor
        uses: plbstl/first-contribution@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-opened-msg: |
            ğŸ‘‹ Bonjour @{fc-author} !

            Merci dâ€™avoir ouvert ta **premiÃ¨re issue** ğŸ‰  
            Nous apprÃ©cions ta contribution et nous allons y jeter un Å“il trÃ¨s bientÃ´t.

            Si tu veux participer au dÃ©veloppement du projet, nâ€™hÃ©site pas Ã  regarder le fichierÂ `CONTRIBUTING.md` et notre [Code of Conduct](./CODE_OF_CONDUCT.md).

            Bienvenue dans la communautÃ© ğŸ’«

      - name: Comment on every new issue
        uses: peter-evans/create-or-update-comment@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.issue.number }}
          body: |
            âœ… Merci pour la crÃ©ation de cette issue !  
            Nous avons bien reÃ§u votre message et allons travailler dessus dÃ¨s que possible.  
            Un membre de lâ€™Ã©quipe reviendra vers vous sous peu.
